### PR TITLE
Add MimeType checking in Router

### LINKED ISSUE #25: Files in public directory being opened as UTF8 Strings
I'm trying to load images from the public directory but it seems from looking at the router code that anything loaded from the public directory needs to be source code—like css or js files.

``` swift
// In Router.swift
if let body = String(data:contents!, encoding: NSUTF8StringEncoding) {
    return Response(.Ok, contentType: "text/plain; charset=utf8", body: body)
}
```

We should be able to also load images and other assets from that directory. Also CSS files and JS files should return a different mimetype than `text/plain`.

### PR DESCRIPTION
**Pull request by califrench**
This adds support for the `mimeType()` function on `String?` types. The
previous implementation allowed to pass nil values to the internal
`MimeType(ext: String?) -> String` function but `.mimeType()` could
never be called on a nil String because that was an extension on the
`String` type.
This allows us to do this

``` swift
let testString :String? = nil
testString.mimeType() //  -> "application/octet-stream"
```

Instead of this

``` swift
let testString : String? = nil
(testString ?? "").mimeType() // -> "application/octet-stream"
```

Or worse

``` swift
let testString : String? = nil
testString.extension?.mimeType ?? "application/octet-stream" // ->"application/octet-stream"
```

This new implementation is used in the router and fixes #25

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
@califrench thanks, but I don't think that it's great idea. We should stick with [Optional Chaining](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/OptionalChaining.html).

**Comment by califrench** [comment]
@sauliusgrigaitis Okay I'll update the code to use optional chaining instead just as in my second example

**Comment by sauliusgrigaitis** [comment]
@califrench probably we can go with this solution for now. Please make one commit. And add test :)

**Comment by califrench** [comment]
@sauliusgrigaitis Done! Hopefully the tests pass as I am not able to run them locally

**Comment by sauliusgrigaitis** [comment]
@califrench please squash into one commit every time :)

**Comment by califrench** [comment]
Is there a GIT way to merge many commits into one?

Best,

Scott Gauthreaux
Developer
www.scottgauthreaux.com

**Comment by califrench** [comment]
The whole PR?

Best,

Scott Gauthreaux
Developer
www.scottgauthreaux.com

**Comment by sauliusgrigaitis** [comment]
[Yes](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes)

**Comment by sauliusgrigaitis** [comment]
@califrench please check latest code - you now can run tests on OSX!!!!!!!11!!!!!!!!1!!!!111 Please rebase your PR against latest master.

**Comment by califrench** [comment]
Hi @sauliusgrigaitis thanks for the link and I'll do ASAP. Stoked about the 2.2 release in XCode and our migration over to XCTest

**Pull request closed without merging**
