### PR TITLE
Update README.md with a code quality badge

### PR DESCRIPTION
**Pull request by grodowski**
Please consider adding the badge and check out the generated quality report. I hope codebeat can help all contributors deliver quality code and help newcomers dive into the codebase by starting with small refactorings.

[codebeat badge](https://codebeat.co/projects/github-com-necolt-swifton)

Disclaimer: I am the co-author of the tool and we've recently released Swift support. I'd love to hear your feedback

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
@grodowski thanks! Can I somehow check violations before commiting?

**Comment by grodowski** [comment]
@sauliusgrigaitis unfortunately no, but we have it in our pipeline. If you have any suggestions on how it should be implemented, please let me know :)

**Comment by sauliusgrigaitis** [comment]
@grodowski here is what we do at [NECOLT](http://necolt.com/):
- We set current code style/code smells etc. violations number. For new projects it's zero obviously.
- CI is configured to check each build and ensure that this number never increases. Actually this number tends to decrease, because our developers naturally improve code over time.
- Before pushing to repo everyone checks did they introduce any new violations. No one wants to push code with new violations. For this we use such tools as [reek-git](https://github.com/necolt/reek-git) or [rubocop-git](https://github.com/m4i/rubocop-git)

I'm happy to use your tool when you have one that checks violations before pushing.

**Comment by grodowski** [comment]
@sauliusgrigaitis Congrats on using reek and rubocop - we also use them, as codebeat's frontend is a Ruby application 🙃. Codebeat however is aimed at providing a high level overview and be a complementary tool to local linters + we support different languages and multi-language analysis. A good news for you is that we are currently working on Github PR integration allowing users to check a delta of issues and grades before merging.

**Comment by sauliusgrigaitis** [comment]
@grodowski thanks, please let me know when that PR integration is completed, so we can probably start to use it.

**Comment by sauliusgrigaitis** [comment]
OK, let's try it. Could you also tell how your product is better comparing to OS alternatives such us:
- https://github.com/realm/SwiftLint
- https://github.com/sleekbyte/tailor

**Pull request merged**
